### ISSUE TITLE
import "github.com/blackjack/webcam" errors

### ISSUE THREAD

**Issue by girs1982** [blackjack/webcam#17]
import-im6.q16: unable to open X server `' @ error/import.c/ImportImageCommand/358.

**Comment by fabian-z** [comment]
It seems you are trying to run this line of Go code in your terminal / command shell instead of putting it in a source (.go) file and compiling it.  The error message does not indicate a problem with the library or your setup. It is thrown by an ImageMagick component named "import" which gets run by your shell.

I would recommend you to start working from introduction tutorials for Go (e.g. https://gobyexample.com/hello-world or pick one from https://github.com/avelino/awesome-go#tutorials).

Hope I could help you :smile:

**Comment by girs1982** [comment]
i done it on python ,go not need now

**Comment by fabian-z** [comment]
Well, it seems like you can have [the same problem](https://stackoverflow.com/questions/19507096/python-error-import-unable-to-open-x-server) with python :wink: 

Either way, glad you got your problem solved - please close the issue in this case.
